name: Gatsby Deploy

on:
  push:
    branches: main

env:
  GH_TOKEN: ${{ secrets.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 }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Config
        run: |
          git config --global user.email "dz03dube@gmail.com"
          git config --global user.name "darrendube"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Deploy
        run: npm run deploy:ci
