name: Build and Deploy GitHub Pages

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Node.js and dependencies (if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install Gatsby CLI or other build tools (if needed)
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      # Install project dependencies (if needed)
      - name: Install dependencies
        run: npm install

      # Build Gatsby site (replace with your build command)
      - name: Build site
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Adjust to your build output directory
